max_epochs: 20
accelerator: cuda
batch_size: 128
layer_type: continuous2d
train_fraction: 1.0
rescale_output: False
periodicity: 2.0
nonlinearity: False
latent_dim: 128
gradient_clip_val: 0.0
segments: 2
n: 2
encoder:
  n: ${n} # polynomial order
  channels: [3, 32, 64, 128]
  segments: ${segments}
  kernel_size: [3, 3, 3]
  stride: 2
  periodicity: ${periodicity}
  normalization: null # batch normalization option
  padding: 1
decoder:
  n: ${n}
  channels: [128, 64, 32, 16, 3]
  segments: ${segments}
  kernel_size: [3, 3, 3, 4]
  stride: 2
  periodicity: ${periodicity}
  normalization: null # batch normalization
  padding: 0
mlp :
  layer_type: continuous
  n: ${n}
  layers: 1 # hidden layers
  width : 64 # hidden width
  segments: ${segments}

defaults:
  - optimizer: lion

