max_epochs: 1
accelerator: 'gpu'

layer_type: continuous2d
train_fraction: 1.0
rescale_output: False
linear_output: True
periodicity: 2.0
lr: 0.001
nonlinearity: False

net :
  layer_type: continuous2d

data:
  classes: 100
  num_workers: 10
  batch_size: 128

defaults:
  - optimizer: lion
  - net: high_order_conv
