max_epochs: 100
gpus: 1 
n: 3
batch_size: 16 
segments: 2
layer_type: polynomial 
train_fraction: 1.0
periodicity: 2.0

# When using products setting linear_part=1.0
# keeps the linear part of the product, while
# setting to 0 removes it.  Helpful if you don't
# want the linear part to dominate.
linear_part: 1.0