max_epochs: 100
accelerator: 'gpu'
batch_size: 256

train_fraction: 1.0
val_fraction: 1.0
periodicity: 2.0

gradient_clip_val: 0

mlp :
  
  n: 2  
  dropout: 0.0
  # target final polynomial order for refinement
  target_n: 5
  
  segments: 2
  layer_type: polynomial

  # Set to true to do polynomial refinement
  p_refine: False
  normalize: max_abs # l2 or False

  input :
    width: 784
    segments : ${mlp.segments}
    n : ${mlp.n}
  hidden :
    width : 20
    layers : 1
    segments : ${mlp.segments}
    n : ${mlp.n}
  output :
    width : 10
    segments : ${mlp.segments}
    n : ${mlp.n}

defaults:
  - optimizer: lion