max_epochs: 1
gpus: 1
n: 5
batch_size: 128
segments: 2
layer_type: continuous2d
train_fraction: 1.0
rescale_output: False
linear_output: True
periodicity: 2.0
lr: 0.001
nonlinearity: False
encoder:
  n: [2] # polynomial order
  channels: [3, 5]
  segments: [2]
  kernel_size: [5]
  periodicity: 2.0
  normalization: null # batch normalization option
decoder:
  n: [2]
  channels: [5, 3]
  segments: [2]
  kernel_size: [32]
  periodicity: 2.0
  normalization: null # batch normalization
