max_epochs: 1
gpus: 1
batch_size: 128
layer_type: continuous2d
train_fraction: 1.0
rescale_output: False
periodicity: 2.0
lr: 1.0e-5
nonlinearity: False
latent_dim: 128
gradient_clip_val: 0.0
segments: 40
n: 2
encoder:
  n: ${n} # polynomial order
  channels: [3, 10, 40, 80]
  segments: ${segments}
  kernel_size: [3, 3, 3]
  stride: 2
  periodicity: ${periodicity}
  normalization: null # batch normalization option
decoder:
  n: ${n}
  channels: [80, 40, 10, 3, 3]
  segments: ${segments}
  kernel_size: [3, 3, 3, 4]
  stride: 2
  periodicity: ${periodicity}
  normalization: null # batch normalization
