max_epochs: 1
gpus: 1
batch_size: 128
layer_type: continuous2d
train_fraction: 1.0
rescale_output: False
periodicity: 2.0
lr: 1.0e-5
nonlinearity: False
latent_dim: 128
gradient_clip_val: 0.0
encoder:
  n: [3, 3, 3] # polynomial order
  channels: [3, 10, 40, 80]
  #segments: [10, 10, 10]
  segments: [40, 40, 40]
  kernel_size: [3, 3, 3]
  stride: [2, 2, 2]
  periodicity: ${periodicity}
  normalization: null # batch normalization option
decoder:
  n: [3, 3, 3, 3]
  channels: [80, 40, 10, 3, 3]
  #segments: [10, 10, 10, 10]
  segments: [40, 40, 40, 40]
  kernel_size: [3, 3, 3, 4]
  stride: [2, 2, 2, 2]
  periodicity: ${periodicity}
  normalization: null # batch normalization
