max_epochs: 1
gpus: 1
n: 3
batch_size: 128
segments: 2
layer_type: continuous2d
train_fraction: 1.0
rescale_output: False
linear_output: True
periodicity: 2.0
lr: 1.0e-4
nonlinearity: False
latent_dim: 128
gradient_clip_val: 5.0
encoder:
  n: [2, 2, 2] # polynomial order
  channels: [3, 10, 40, 80]
  #segments: [10, 10, 10]
  segments: [40, 40, 40]
  kernel_size: [3, 3, 3]
  stride: [2, 2, 2]
  periodicity: ${periodicity}
  normalization: null # batch normalization option
decoder:
  n: [2, 2, 2, 2]
  channels: [80, 40, 10, 3, 3]
  #segments: [10, 10, 10, 10]
  segments: [40, 40, 40, 40]
  kernel_size: [3, 3, 3, 4]
  stride: [2, 2, 2, 2]
  periodicity: ${periodicity}
  normalization: null # batch normalization
